package Model;
// Generated 23-10-2017 13:36:15 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * PermisosDetalles generated by hbm2java
 */
public class PermisosDetalles  implements java.io.Serializable {


     private byte[] idDetallePermiso;
     private Usuarios usuarios;
     private Permisos permisos;
     private Date fechaemision;
     private BigDecimal estado;
     private Date fechainicio;
     private Date fechafin;
     private BigDecimal dias;

    public PermisosDetalles() {
    }

    public PermisosDetalles(byte[] idDetallePermiso, Usuarios usuarios, Permisos permisos, Date fechaemision, BigDecimal estado, Date fechainicio, Date fechafin, BigDecimal dias) {
       this.idDetallePermiso = idDetallePermiso;
       this.usuarios = usuarios;
       this.permisos = permisos;
       this.fechaemision = fechaemision;
       this.estado = estado;
       this.fechainicio = fechainicio;
       this.fechafin = fechafin;
       this.dias = dias;
    }
   
    public byte[] getIdDetallePermiso() {
        return this.idDetallePermiso;
    }
    
    public void setIdDetallePermiso(byte[] idDetallePermiso) {
        this.idDetallePermiso = idDetallePermiso;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Permisos getPermisos() {
        return this.permisos;
    }
    
    public void setPermisos(Permisos permisos) {
        this.permisos = permisos;
    }
    public Date getFechaemision() {
        return this.fechaemision;
    }
    
    public void setFechaemision(Date fechaemision) {
        this.fechaemision = fechaemision;
    }
    public BigDecimal getEstado() {
        return this.estado;
    }
    
    public void setEstado(BigDecimal estado) {
        this.estado = estado;
    }
    public Date getFechainicio() {
        return this.fechainicio;
    }
    
    public void setFechainicio(Date fechainicio) {
        this.fechainicio = fechainicio;
    }
    public Date getFechafin() {
        return this.fechafin;
    }
    
    public void setFechafin(Date fechafin) {
        this.fechafin = fechafin;
    }
    public BigDecimal getDias() {
        return this.dias;
    }
    
    public void setDias(BigDecimal dias) {
        this.dias = dias;
    }




}


