package Model;
// Generated 23-10-2017 13:36:15 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Permisos generated by hbm2java
 */
public class Permisos implements java.io.Serializable {

    private byte[] idPermiso;
    private Usuarios usuarios;
    private TiposPermisos tiposPermisos;
    private String recursolegal;
    private String tipopermiso;
    private Date fecha;
    private Set resolucionesDetalles = new HashSet(0);
    private Set permisosDetalleses = new HashSet(0);

    public Permisos() {
    }

    public Permisos(byte[] idPermiso, Usuarios usuarios, TiposPermisos tiposPermisos) {
        this.idPermiso = idPermiso;
        this.usuarios = usuarios;
        this.tiposPermisos = tiposPermisos;
    }

    public Permisos(byte[] idPermiso, Usuarios usuarios, TiposPermisos tiposPermisos, String recursolegal, String tipopermiso, Date fecha, Set resolucionesDetalles, Set permisosDetalleses) {
        this.idPermiso = idPermiso;
        this.usuarios = usuarios;
        this.tiposPermisos = tiposPermisos;
        this.recursolegal = recursolegal;
        this.tipopermiso = tipopermiso;
        this.fecha = fecha;
        this.resolucionesDetalles = resolucionesDetalles;
        this.permisosDetalleses = permisosDetalleses;
    }

    public byte[] getIdPermiso() {
        return this.idPermiso;
    }

    public void setIdPermiso(byte[] idPermiso) {
        this.idPermiso = idPermiso;
    }

    public Usuarios getUsuarios() {
        return this.usuarios;
    }

    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }

    public TiposPermisos getTiposPermisos() {
        return this.tiposPermisos;
    }

    public void setTiposPermisos(TiposPermisos tiposPermisos) {
        this.tiposPermisos = tiposPermisos;
    }

    public String getRecursolegal() {
        return this.recursolegal;
    }

    public void setRecursolegal(String recursolegal) {
        this.recursolegal = recursolegal;
    }

    public String getTipopermiso() {
        return this.tipopermiso;
    }

    public void setTipopermiso(String tipopermiso) {
        this.tipopermiso = tipopermiso;
    }

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public Set getResolucionesDetalles() {
        return this.resolucionesDetalles;
    }

    public void setResolucionesDetalles(Set resolucionesDetalles) {
        this.resolucionesDetalles = resolucionesDetalles;
    }

    public Set getPermisosDetalleses() {
        return this.permisosDetalleses;
    }

    public void setPermisosDetalleses(Set permisosDetalleses) {
        this.permisosDetalleses = permisosDetalleses;
    }

}
