package Model;
// Generated 13-11-2017 13:26:02 by Hibernate Tools 4.3.1


import java.util.Date;


/**
 * Auditor generated by hbm2java
 */
public class Auditor  implements java.io.Serializable {


     private byte[] idAud;
     private Date fechaincidencia;
     private String usuarioautor;
     private String detalleconsulta;

    public Auditor() {
    }

    public Auditor(byte[] idAud, Date fechaincidencia, String usuarioautor, String detalleconsulta) {
       this.idAud = idAud;
       this.fechaincidencia = fechaincidencia;
       this.usuarioautor = usuarioautor;
       this.detalleconsulta = detalleconsulta;
    }
   
    public byte[] getIdAud() {
        return this.idAud;
    }
    
    public void setIdAud(byte[] idAud) {
        this.idAud = idAud;
    }
    public Date getFechaincidencia() {
        return this.fechaincidencia;
    }
    
    public void setFechaincidencia(Date fechaincidencia) {
        this.fechaincidencia = fechaincidencia;
    }
    public String getUsuarioautor() {
        return this.usuarioautor;
    }
    
    public void setUsuarioautor(String usuarioautor) {
        this.usuarioautor = usuarioautor;
    }
    public String getDetalleconsulta() {
        return this.detalleconsulta;
    }
    
    public void setDetalleconsulta(String detalleconsulta) {
        this.detalleconsulta = detalleconsulta;
    }




}


