package Model;
// Generated 13-11-2017 13:26:02 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Permisos generated by hbm2java
 */
public class Permisos  implements java.io.Serializable {


     private byte[] idPermiso;
     private Usuarios usuarios;
     private TiposPermisos tiposPermisos;
     private String tipopermiso;
     private BigDecimal idIncrement;
     private Set permisosDetalleses = new HashSet(0);
     private Set resolucionesDetalles = new HashSet(0);

    public Permisos() {
    }

	
    public Permisos(byte[] idPermiso, Usuarios usuarios, TiposPermisos tiposPermisos, BigDecimal idIncrement) {
        this.idPermiso = idPermiso;
        this.usuarios = usuarios;
        this.tiposPermisos = tiposPermisos;
        this.idIncrement = idIncrement;
    }
    public Permisos(byte[] idPermiso, Usuarios usuarios, TiposPermisos tiposPermisos, String tipopermiso, BigDecimal idIncrement, Set permisosDetalleses, Set resolucionesDetalles) {
       this.idPermiso = idPermiso;
       this.usuarios = usuarios;
       this.tiposPermisos = tiposPermisos;
       this.tipopermiso = tipopermiso;
       this.idIncrement = idIncrement;
       this.permisosDetalleses = permisosDetalleses;
       this.resolucionesDetalles = resolucionesDetalles;
    }
   
    public byte[] getIdPermiso() {
        return this.idPermiso;
    }
    
    public void setIdPermiso(byte[] idPermiso) {
        this.idPermiso = idPermiso;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public TiposPermisos getTiposPermisos() {
        return this.tiposPermisos;
    }
    
    public void setTiposPermisos(TiposPermisos tiposPermisos) {
        this.tiposPermisos = tiposPermisos;
    }
    public String getTipopermiso() {
        return this.tipopermiso;
    }
    
    public void setTipopermiso(String tipopermiso) {
        this.tipopermiso = tipopermiso;
    }
    public BigDecimal getIdIncrement() {
        return this.idIncrement;
    }
    
    public void setIdIncrement(BigDecimal idIncrement) {
        this.idIncrement = idIncrement;
    }
    public Set getPermisosDetalleses() {
        return this.permisosDetalleses;
    }
    
    public void setPermisosDetalleses(Set permisosDetalleses) {
        this.permisosDetalleses = permisosDetalleses;
    }
    public Set getResolucionesDetalles() {
        return this.resolucionesDetalles;
    }
    
    public void setResolucionesDetalles(Set resolucionesDetalles) {
        this.resolucionesDetalles = resolucionesDetalles;
    }




}


