package Model;
// Generated 13-11-2017 13:26:02 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * ResolucionesDetalle generated by hbm2java
 */
public class ResolucionesDetalle  implements java.io.Serializable {


     private byte[] idDetalleResolucion;
     private Resoluciones resoluciones;
     private Permisos permisos;
     private String justificacion;
     private BigDecimal recursolegalafecto;
     private Date fechaemision;

    public ResolucionesDetalle() {
    }

	
    public ResolucionesDetalle(byte[] idDetalleResolucion, Resoluciones resoluciones, Permisos permisos, String justificacion, Date fechaemision) {
        this.idDetalleResolucion = idDetalleResolucion;
        this.resoluciones = resoluciones;
        this.permisos = permisos;
        this.justificacion = justificacion;
        this.fechaemision = fechaemision;
    }
    public ResolucionesDetalle(byte[] idDetalleResolucion, Resoluciones resoluciones, Permisos permisos, String justificacion, BigDecimal recursolegalafecto, Date fechaemision) {
       this.idDetalleResolucion = idDetalleResolucion;
       this.resoluciones = resoluciones;
       this.permisos = permisos;
       this.justificacion = justificacion;
       this.recursolegalafecto = recursolegalafecto;
       this.fechaemision = fechaemision;
    }
   
    public byte[] getIdDetalleResolucion() {
        return this.idDetalleResolucion;
    }
    
    public void setIdDetalleResolucion(byte[] idDetalleResolucion) {
        this.idDetalleResolucion = idDetalleResolucion;
    }
    public Resoluciones getResoluciones() {
        return this.resoluciones;
    }
    
    public void setResoluciones(Resoluciones resoluciones) {
        this.resoluciones = resoluciones;
    }
    public Permisos getPermisos() {
        return this.permisos;
    }
    
    public void setPermisos(Permisos permisos) {
        this.permisos = permisos;
    }
    public String getJustificacion() {
        return this.justificacion;
    }
    
    public void setJustificacion(String justificacion) {
        this.justificacion = justificacion;
    }
    public BigDecimal getRecursolegalafecto() {
        return this.recursolegalafecto;
    }
    
    public void setRecursolegalafecto(BigDecimal recursolegalafecto) {
        this.recursolegalafecto = recursolegalafecto;
    }
    public Date getFechaemision() {
        return this.fechaemision;
    }
    
    public void setFechaemision(Date fechaemision) {
        this.fechaemision = fechaemision;
    }




}


