package Model;
// Generated 13-11-2017 13:26:02 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private byte[] idUsuario;
     private Unidades unidades;
     private Perfiles perfiles;
     private String nombre;
     private String email;
     private String contrasena;
     private String rut;
     private BigDecimal eliminado;
     private Set permisoses = new HashSet(0);
     private Set permisosDetalleses = new HashSet(0);

    public Usuarios() {
    }

	
    public Usuarios(byte[] idUsuario, Unidades unidades, Perfiles perfiles, String nombre, String email, String contrasena, String rut, BigDecimal eliminado) {
        this.idUsuario = idUsuario;
        this.unidades = unidades;
        this.perfiles = perfiles;
        this.nombre = nombre;
        this.email = email;
        this.contrasena = contrasena;
        this.rut = rut;
        this.eliminado = eliminado;
    }
    public Usuarios(byte[] idUsuario, Unidades unidades, Perfiles perfiles, String nombre, String email, String contrasena, String rut, BigDecimal eliminado, Set permisoses, Set permisosDetalleses) {
       this.idUsuario = idUsuario;
       this.unidades = unidades;
       this.perfiles = perfiles;
       this.nombre = nombre;
       this.email = email;
       this.contrasena = contrasena;
       this.rut = rut;
       this.eliminado = eliminado;
       this.permisoses = permisoses;
       this.permisosDetalleses = permisosDetalleses;
    }
   
    public byte[] getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(byte[] idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Unidades getUnidades() {
        return this.unidades;
    }
    
    public void setUnidades(Unidades unidades) {
        this.unidades = unidades;
    }
    public Perfiles getPerfiles() {
        return this.perfiles;
    }
    
    public void setPerfiles(Perfiles perfiles) {
        this.perfiles = perfiles;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getRut() {
        return this.rut;
    }
    
    public void setRut(String rut) {
        this.rut = rut;
    }
    public BigDecimal getEliminado() {
        return this.eliminado;
    }
    
    public void setEliminado(BigDecimal eliminado) {
        this.eliminado = eliminado;
    }
    public Set getPermisoses() {
        return this.permisoses;
    }
    
    public void setPermisoses(Set permisoses) {
        this.permisoses = permisoses;
    }
    public Set getPermisosDetalleses() {
        return this.permisosDetalleses;
    }
    
    public void setPermisosDetalleses(Set permisosDetalleses) {
        this.permisosDetalleses = permisosDetalleses;
    }




}


